/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Full Time
 */
public class Facility_Category_Details extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs =null;
    PreparedStatement pst = null;
    
    public void table_load(){
    
        try {
             DefaultTableModel model = (DefaultTableModel) table.getModel();
             model.setRowCount(0);
             pst = con.prepareStatement("select * from facility_category");
             rs = pst.executeQuery();
             while(rs.next()){                
                 model.addRow(new Object[]{rs.getString("no"), rs.getString("name"), rs.getString("des")});                              
             }
             
        } catch (Exception e) {
            System.out.println(e);
        }
    
    }
    
    public void reset(){
    
        cno.setText("");
        txt1.setText("");
        cname.setText("");
        txt2.setText("");
        cdes.setText("");
        csearchby.setSelectedIndex(0);
        csearchfor.setText("");
        table_load();
        
    }
    
    public void search(){
    
        
    
        if(csearchfor.getText().trim().equals("")){
            table_load();
        }
        else{
        
            if(csearchby.getSelectedIndex()==0){
            
                try {
                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    model.setRowCount(0);
                    pst = con.prepareStatement("select * from facility_category where no like ?");
                    pst.setString(1, "%"+csearchfor.getText().trim()+"%");
                    rs = pst.executeQuery();
                    while(rs.next()){                
                        model.addRow(new Object[]{rs.getString("no"), rs.getString("name"), rs.getString("des")});                              
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }      
            }
            
            if(csearchby.getSelectedIndex()==1){
            
                try {
                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    model.setRowCount(0);
                    pst = con.prepareStatement("select * from facility_category where name like ?");
                    pst.setString(1, "%"+csearchfor.getText().trim()+"%");
                    rs = pst.executeQuery();
                    while(rs.next()){                
                        model.addRow(new Object[]{rs.getString("no"), rs.getString("name"), rs.getString("des")});                              
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }      
            }
                                  
        }
        
        
    }
    
    
    /**
     * Creates new form Facility_Category_Details
     */
    public Facility_Category_Details() {
        initComponents();
        cno.setEnabled(false);
        con = Dbconnect.connect();
        table_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt2 = new javax.swing.JLabel();
        modify = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        csearchby = new javax.swing.JComboBox<>();
        csearchfor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cno = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        txt1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cdes = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modify.setText("MODIFY");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        jButton4.setText("DASHBOARD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category No", "Category Name", "Description"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jLabel5.setText("Search by  :");

        jLabel6.setText("Search for :");

        csearchby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category No", "Category Name" }));
        csearchby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csearchbyActionPerformed(evt);
            }
        });

        csearchfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csearchforActionPerformed(evt);
            }
        });
        csearchfor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                csearchforKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("FACILITY CATEGORY DETAILS");

        jLabel2.setText("Category No       :");

        jLabel3.setText("Category Name  :");

        jLabel4.setText("Description          :");

        cno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnoActionPerformed(evt);
            }
        });

        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });

        cdes.setColumns(20);
        cdes.setRows(5);
        cdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cdesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(cdes);

        jButton1.setText("NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        done.setText("DONE");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(cno, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(done)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modify)
                        .addGap(47, 47, 47)
                        .addComponent(remove)
                        .addGap(49, 49, 49)
                        .addComponent(reset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csearchfor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csearchby, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(252, 252, 252))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(csearchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(csearchfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(done)
                    .addComponent(modify)
                    .addComponent(remove)
                    .addComponent(reset))
                .addGap(21, 21, 21)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed

        if(cno.getText().trim().equals("")||cname.getText().trim().equals("")){

            if(cno.getText().trim().equals("")){
                txt1.setText("Empty");
            }
            if(cname.getText().trim().equals("")){
                txt2.setText("Empty");
            }
            

        }else{

            try {
                pst = con.prepareStatement("select * from facility_category where no = ?");
                pst.setString(1, cno.getText());
                rs = pst.executeQuery();
                if(rs.next()){
                    pst = con.prepareStatement("update facility_category set name = ?,des = ?  where no = ?");
                    pst.setString(3, cno.getText().trim());
                    pst.setString(1, cname.getText().trim());
                    pst.setString(2, cdes.getText().trim());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully Updated");
                    reset();
                }
                else{
                    JOptionPane.showMessageDialog(null, "There is no record under this Category No");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error");
                System.out.println(e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed

        if(cno.getText().trim().equals("")){
            txt1.setText("Empty");
        }
        else{
            try {
                pst = con.prepareStatement("select * from facility_category where no = ?");
                pst.setString(1, cno.getText());
                rs = pst.executeQuery();
                if(rs.next()){
                    pst = con.prepareStatement("delete from facility_category where no = ?");
                    pst.setString(1, cno.getText().trim());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully Deleted");
                    reset();
                }
                else{
                    JOptionPane.showMessageDialog(null, "There is no record under this Category No");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error");
                System.out.println(ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Dashboard x = new Dashboard();
        x.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int r = table.getSelectedRow();
        String selected = (String) table.getValueAt(r, 0);
        try {
            pst = con.prepareStatement("select * from facility_category where no = ?");
            pst.setString(1, selected);
            rs = pst.executeQuery();
            if(rs.next()){

                txt1.setText("");
                txt2.setText("");

                cno.setText(rs.getString("no"));
                cname.setText(rs.getString("name"));
                cdes.setText(rs.getString("des"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void csearchbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csearchbyActionPerformed



        // TODO add your handling code here:
    }//GEN-LAST:event_csearchbyActionPerformed

    private void csearchforKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csearchforKeyReleased
        search();
        // TODO add your handling code here:
    }//GEN-LAST:event_csearchforKeyReleased

    private void cnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnoActionPerformed

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        if(cname.getText().trim().equals("")){
            txt2.setText("Empty");
        }
        else{
            txt2.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cnameKeyReleased

    private void cdesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdesKeyReleased

    }//GEN-LAST:event_cdesKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            pst = con.prepareStatement("select no from facility_category");
            rs = pst.executeQuery();
            String last = "0";

            while(rs.next()){
                last = rs.getString("no");
            }

            Integer newnumber = Integer.parseInt(last)+1;
            String newno = String.valueOf(newnumber);
            reset();
            cno.setText(newno);

        } catch (Exception e) {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed

        if(cno.getText().trim().equals("")||cname.getText().trim().equals("")){

            if(cno.getText().trim().equals("")){
                txt1.setText("Empty");
            }
            if(cname.getText().trim().equals("")){
                txt2.setText("Empty");
            }
            

        }
        else{

            try {
                pst = con.prepareStatement("select * from facility_category where no = ?");
                pst.setString(1, cno.getText());
                rs = pst.executeQuery();

                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This item Category No already has a record.");
                }

                else{

                    pst = con.prepareStatement("insert into facility_category values(?,?,?)");
                    pst.setString(1, cno.getText());
                    pst.setString(2, cname.getText());
                    pst.setString(3, cdes.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully Added");
                    reset();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error");
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        reset();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void csearchforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csearchforActionPerformed
    search();
    }//GEN-LAST:event_csearchforActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facility_Category_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facility_Category_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facility_Category_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facility_Category_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facility_Category_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cdes;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cno;
    private javax.swing.JComboBox<String> csearchby;
    private javax.swing.JTextField csearchfor;
    private javax.swing.JButton done;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modify;
    private javax.swing.JButton remove;
    private javax.swing.JButton reset;
    private javax.swing.JTable table;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
